### ISSUE TITLE
把项目迁移到nonebot2以避免风控

### ISSUE THREAD

**Issue by sunzeyuande** [joeyHXD/aoe4_watcher_bot#2]
大佬方便把项目迁移到nonebot2（https://github.com/nonebot/nonebot2）+LLOneBot(https://github.com/LLOneBot/LLOneBot)吗？似乎还没有风控的问题，代码我大概看了下应该只涉及run.py。如果没空迁移的话能否留个联系方式向你请教一些代码的细节？

**Comment by joeyHXD** [comment]
好啊，我还以为这个项目没人关注hhh
我的QQ：2241192063

**Comment by joeyHXD** [comment]
nb2我没用过，我也不知道怎么迁移
